sepolia:
    chainId: 11155111
    url: ''
    deployerWalletAlias: 'sepolia-deployer-wallet'
    main: ''
    wrappedEther: ''

ethereum:
    chainId: 1
    url: ''
    deployerWalletAlias: 'ethereum-deployer-wallet'
    main: ''
    wrappedEther: ''
