sepolia:
    chainId: 11155111
    url: ''
    deployerWalletAlias: 'digital-original-sepolia-deployer-wallet'
    main: ''
    wrappedEther: ''

ethereum:
    chainId: 1
    url: ''
    deployerWalletAlias: 'digital-original-ethereum-deployer-wallet'
    main: ''
    wrappedEther: ''
